# Generated by Django 4.0.1 on 2022-03-17 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import supermarket.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('image', models.ImageField(null=True, upload_to=supermarket.models.product_main_image_upload)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('Number_of_inventory', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ImageField(null=True, upload_to=supermarket.models.product_main_image_upload)),
                ('active', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(blank=True, to='supermarket.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SuperMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=256)),
                ('banner', models.ImageField(upload_to=supermarket.models.banner_upload)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superMarkets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to=supermarket.models.product_gallery_upload)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='super_market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='supermarket.supermarket'),
        ),
    ]
